services:
  - type: web
    name: gainsgalore
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn gainsgalore.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
    autoDeploy: true
    postDeployCommand: "python manage.py migrate"
